[versions]
springBootVersion = "3.3.5"
springDependencyManagementVersion = "1.1.6"
spotlessVersion = "6.25.0"

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBootVersion"}
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion"}
spotless = { id = "com.diffplug.spotless", version.ref = "spotlessVersion"}