[versions]
springBoot = "3.3.5"
springDependencyManagement = "1.1.6"
spotless = "6.25.0"
sonarqube = "5.1.0.4882"
nebulaRelease = "19.0.10"

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot"}
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement"}
spotless = { id = "com.diffplug.spotless", version.ref = "spotless"}
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube"}
nebulaRelease = { id = "nebula.release", version.ref = "nebulaRelease"}