name: CI

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
    types:
      - labeled

jobs:
  build:

    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run checks')
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0

    - name: Build
      run: ./gradlew build sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
