name: Sonar on PR

on:
  pull_request:
    types: [labeled]

jobs:
  sonar-on-pr:
    if: |
      github.event.label.name == 'run-sonar' &&
      github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0

    - name: Build and Test
      run: ./gradlew build

    - name: Sonar
      run: ./gradlew sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
